import streamlit as st


def generate_report(analysis: dict) -> str:
    """Generate a markdown report from the analysis dict."""
    lines = []
    lines.append("# FDE Codebase Scout - Analysis Report\n")

    lines.append("## Executive Summary\n")
    lines.append(f"{analysis.get('summary', 'No summary available.')}\n")

    lines.append("## Health Score\n")
    lines.append(f"**Score: {analysis.get('health_score', 'N/A')} / 100**\n")

    lines.append("## Architecture Breakdown\n")
    lines.append("| Layer | Technology | Status | Notes |")
    lines.append("|-------|-----------|--------|-------|")
    for layer in analysis.get("architecture", []):
        status_emoji = {"ok": "OK", "warn": "WARN", "error": "ERROR"}.get(layer.get("status", "ok"), "?")
        lines.append(f"| {layer['layer']} | {layer['tech']} | {status_emoji} | {layer['notes']} |")
    lines.append("")

    lines.append("## Quick Wins\n")
    lines.append("| # | Title | Impact | Effort (SP) | Risk | Category |")
    lines.append("|---|-------|--------|-------------|------|----------|")
    for i, win in enumerate(analysis.get("quick_wins", []), 1):
        lines.append(f"| {i} | {win['title']} | {win['impact']} | {win['effort_sp']} | {win['risk']} | {win.get('category', '-')} |")
    lines.append("")

    lines.append("## Onboarding Sprint Plan\n")
    for week in analysis.get("onboarding_plan", []):
        lines.append(f"### {week['week']} - {week['focus']}")
        lines.append(f"- **Story Points:** {week['story_points']}")
        lines.append(f"- **Tasks:** {week['tasks']}")
        lines.append("")

    total_sp = sum(w.get("story_points", 0) for w in analysis.get("onboarding_plan", []))
    lines.append(f"**Total Story Points: {total_sp}**\n")

    lines.append("## Architecture Diagram\n")
    lines.append("```mermaid")
    lines.append(analysis.get("mermaid_diagram", "graph TD; A[No diagram available]"))
    lines.append("```\n")

    lines.append("---\n")
    lines.append("*Generated by FDE Codebase Scout | Built by Isha Madhurendra*\n")

    return "\n".join(lines)


def render_report(analysis: dict):
    """Render the report preview and download button."""
    report_md = generate_report(analysis)

    st.markdown("""
    <div style="color: #6B6560; font-family: 'DM Mono', monospace; font-size: 10px; letter-spacing: 0.08em; text-transform: uppercase; margin-bottom: 18px;">Export Report</div>
    """, unsafe_allow_html=True)

    st.download_button(
        label="Download Report (.md)",
        data=report_md,
        file_name="fde_codebase_scout_report.md",
        mime="text/markdown",
        use_container_width=True,
    )

    st.markdown("<div style='height: 18px'></div>", unsafe_allow_html=True)

    with st.expander("Preview Report", expanded=True):
        st.markdown(report_md)
